version: "3.9"

services:
  apix:
    container_name: apix
    build: .
    ports:
      - $PORT:$PORT
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    command: bash -c "yarn typeorm migration:generate src/migrations/createTables -d src/data-source && yarn typeorm migration:run -d src/data-source && yarn dev"
    volumes:
      - .:/app

  database:
    container_name: database
    image: postgres:14-alpine
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
   

